### ISSUE TITLE
MSI fails: no azure identity found for request clientID

### ISSUE THREAD

**Issue by vaxxor** [oleewere/fluent-plugin-azurestorage-gen2#11]
MSI not working for me.

* im testing it here manually on the server but fluentd gives same error.

running this from the VM gives me the token:
`curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fstorage.azure.com%2F' -H Metadata:true`

but when i use 
`curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fstorage.azure.com%2F&msi_res_id=/subscriptions/xxxxx' -H Metadata:true`
I'm getting an error: 

> no azure identity found for request clientID

I don't see a way in your code **not** to use msi_res_id.

FYI using msi_res_id + client_id does gives me the token.

`curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fstorage.azure.com%2F&msi_res_id=/subscriptions/xxxxx&client_id=XXXX' -H Metadata:true`

**Comment by matt-carr** [comment]
To save time for others who bump into this: you can just set 
```
azure_instance_msi               ""
```
