### ISSUE TITLE
Support for Azure Government Cloud

### ISSUE THREAD

**Issue by EntityAdam** [oleewere/fluent-plugin-azurestorage-gen2#15]
The URL for the identity authority should be configurable to allow retrieval of the JWT token from either Azure Commercial or Azure Government Cloud.

**Comment by JimMullennix** [comment]
Thanks for getting on this so quickly @oleewere .  Any idea how long before it shows up ready built in the public gem repo?

**Comment by EntityAdam** [comment]
from @oleewere 
> will fix builds before merging this, probably will start using github actions instead of travis ci

I'll see if I can help out with this as well.

**Comment by EntityAdam** [comment]
@oleewere I got a basic build + rake working in Github Actions.  I didn't test pushing the gem because that would just make a mess if I made a mistake.

see here: https://github.com/EntityAdam/fluent-plugin-azurestorage-gen2/blob/build/.github/workflows/gem-push.yaml

**Comment by oleewere** [comment]
@EntityAdam , thanks for looking into this, but it's already in progress - I will just use email + password pair for gem push in the workflow

**Comment by oleewere** [comment]
@EntityAdam done - feel free to close this if it meets your requirements - 0.3.4 version should be available with your changes

**Comment by JimMullennix** [comment]
I'm afraid there's a bug.  The default value for the new substitution does not have https:// in it, and the replacement in the code for authentication does not prepend it, so if you haven't changed your configuration and still want the original default, authentication fails unless you override the authority endpoint with a fully qualified URI with https://login.microsoftonline.com.

**Comment by EntityAdam** [comment]
@JimMullennix Wow I feel dumb. Corrected in PR #17.

@oleewere Thanks a bunch for the response! You are awesome.

**Comment by oleewere** [comment]
ok no problem my eyes also skipped that, 0.3.5 version should be fine

**Comment by oleewere** [comment]
@EntityAdam can i close this issue for now?

**Comment by EntityAdam** [comment]
This is resolved
