### ISSUE TITLE
format option not working

### ISSUE THREAD

**Issue by shibug** [oleewere/fluent-plugin-azurestorage-gen2#2]
I am using the latest version 0.1.4.  When I set the format option to json and include_time_key = true, I expect that the time of the event is injected into the record but it is not happening. Below is my configuration:

> @type azurestorage_gen2
      @log_level debug
      azure_storage_account        storage
      azure_instance_msi           /subscriptions/uami
      azure_container              dev
      auto_create_container        true
      time_slice_format            %Y-%m-%d-%H
      path                         "fluentd/%Y/%m/%d/${tag[1]}"
      azure_object_key_format      %{path}/events-%{time_slice}_%{index}.%{file_extension}
      file_extension               log
      format                       json
      include_time_key             true
      <buffer tag,time>
        @type file
        path /fluentd/buffer
        timekey 1m
        timekey_wait 0s
        timekey_use_utc true
        chunk_limit_size 64m
      </buffer>

The record is the same as in out_file format.

**Comment by oleewere** [comment]
hi @shibug 
formatters are used for I/O operations (temp files), it's not used for chunks if processed directly. but you can use something like adding `store_as` `text` into the config section or format the output before processing by a matcher
