### ISSUE TITLE
Non VM authentication

### ISSUE THREAD

**Issue by danfinn** [oleewere/fluent-plugin-azurestorage-gen2#21]
This isn't an issue per say but I didn't see a discussion section.  I'm a little confused by the Readme.  I'm looking to use this plugin on fluentd containers running on kubernetes.  The readme makes it sound like the only option for authentication is MSI but it also says this only works on VMs?  What is the suggested authentication type for my use case?

**Comment by danfinn** [comment]
I think I got this working using oauth authentication however it's not creating any blobs under the storage container.  I'm not getting any errors or output at all from the plugin.

**Comment by oleewere** [comment]
@danfinn - this worked for other teams using MSI - but i do not have the exact config, so i would recommend oauth 2.0, need some time to investigate this how it was done

**Comment by oleewere** [comment]
(also note, this plugin implementation started as the other plugin had memory issues with azure sdk + ruby http client (that's why libcurl is used), so majority of the usage was on VMs)

**Comment by oleewere** [comment]
if your cluster on AKS, MSI can work (e.g. with using this: https://azure.github.io/aad-pod-identity/docs/concepts/mic/)

**Comment by danfinn** [comment]
I think I got the auth working, at least I’m not getting errors anymore but I’m also not getting anything being written to blob storage. Is there any way to get some debug logging to try to see what’s happening?

**Comment by oleewere** [comment]
most logs are on debug level, maybe you need this:

```
<system>
  log_level debug
</system>
```

**Comment by oleewere** [comment]
opened for too long im closing it for now
