### ISSUE TITLE
store_as option for gzip not working

### ISSUE THREAD

**Issue by shibug** [oleewere/fluent-plugin-azurestorage-gen2#3]
Using the latest version 0.1.4 with store_as option set to gzip.  The blob on ADLS is gzipped successfully.  Upon downloading and unzipping, the file is not readable as text.  Here is my configuration:

> @type azurestorage_gen2
      @log_level debug
      azure_storage_account        storage
      azure_instance_msi           /subscriptions/uami
      azure_container              dev
      auto_create_container        true
      time_slice_format            %Y-%m-%d-%H
      path                         "fluentd/%Y/%m/%d/${tag[1]}"
      azure_object_key_format      %{path}/events-%{time_slice}_%{index}.%{file_extension}
      store_as                     gzip
      <buffer tag,time>
        @type file
        path /fluentd/buffer
        timekey 1m
        timekey_wait 0s
        timekey_use_utc true
        chunk_limit_size 64m
      </buffer>

**Comment by oleewere** [comment]
@shibug, it will work from 0.1.6 (text/plain content type is used for gzip during upload as "application/octet-stream" or "text/plain" are the valid media types)

**Comment by shibug** [comment]
This is working fine with v0.1.6.  thank you.  After applying the below configuration change, I am able to format it back to json and save the file to ADLS in gzip format.  I was also able to inject the time key into the JSON message using this plugin itself.  Here is my current configuration:

> @type azurestorage_gen2
    azure_storage_account   ctbnsfanalytics1
    azure_instance_msi      /subscriptions/uami
    azure_container         dev
    auto_create_container   true
    time_slice_format       %Y-%m-%d-%H
    path                    "fluentd/%Y/%m/%d/${tag[1]}"
    azure_object_key_format "%{path}/${tag[1]}-%{time_slice}_%{index}.%{file_extension}"
    format                  json
    include_time_key        true
    time_format             %Y-%m-%dT%H:%M:%S.%LZ
    store_as                gzip
    <buffer tag,time>
      @type            file
      path             /fluentd/buffer
      timekey          1m
      timekey_wait     0s
      timekey_use_utc  true
      chunk_limit_size 64m
    </buffer>

Thanks for all the help.  Much appreciated
