### ISSUE TITLE
Intermittent InvalidFlushPosition error

### ISSUE THREAD

**Issue by shibug** [oleewere/fluent-plugin-azurestorage-gen2#5]
I am using version 0.1.6 and ran it for 24 hours with 100s of events successfully being appended, compressed and stored on ADLS.  However I have received a few errors as below:

> 2020-01-05 01:35:01 +0000 [warn]: #0 got unrecoverable error in primary and no secondary error_class=Fluent::UnrecoverableError error="Blob flush request failed - code: 400, body: {\"error\":{\"code\":\"InvalidFlushPosition\",\"message\":\"The uploaded data is not contiguous or the position query parameter value is not equal to the length of the file after appending the uploaded data.\\nRequestId:055e3490-201f-0012-7568-c3057f000000\\nTime:2020-01-05T01:35:01.7857259Z\"}}, headers: {\"Content-Length\"=>\"284\", \"Content-Type\"=>\"application/json;charset=utf-8\", \"Server\"=>\"Windows-Azure-HDFS/1.0 Microsoft-HTTPAPI/2.0\", \"x-ms-error-code\"=>\"InvalidFlushPosition\", \"x-ms-request-id\"=>\"055e3490-201f-0012-7568-c3057f000000\", \"x-ms-version\"=>\"2018-11-09\", \"Date\"=>\"Sun, 05 Jan 2020 01:35:01 GMT\"}"

Not sure why am I seeing this?   Looks like this error happens when appending chunk to ADLS and is thrown by Azure blob API.  Is there a better way to debug the problem.  Since the user is not explicitely controlling the content length or how the append happens, I am wondering if this is a bug within this plugin

My fluentd configuration is below:

> @type azurestorage_gen2
      azure_storage_account   myStorage
      azure_instance_msi      /subscriptions/uami
      azure_container         dev
      auto_create_container   true
      time_slice_format       %Y-%m-%d-%H
      path                    "fluentd/%Y/%m/%d/${tag[1]}"
      azure_object_key_format "%{path}/${tag[1]}-%{time_slice}_%{index}.%{file_extension}"
      format                  json
      include_time_key        true
      time_format             %Y-%m-%dT%H:%M:%S.%LZ
      store_as                gzip
      <buffer tag,time>
        @type file
        path /fluentd/buffer
        timekey 5m
        timekey_wait 0s
        timekey_use_utc true
        chunk_limit_size 64m
      </buffer>

**Comment by oleewere** [comment]
@shibug, it's not related with the version changes, i have seen this before, against the exact same data that i'm uploading every time. Im guessing if it's an error in the plugin it should be not that Intermittent. (but could be, i will need to investigate it more deeply), if you enable debug logs, you can see the append and flush position parameters. (could be problem in the plugin, but related with the provider, like calling flush too soon or something similar)
btw, did you noticed any data loss?

edit: you probably face data loss as that is an unrecoverable error (that suppress retries), maybe would make sense to change that during flush and have an option to retry. with this we can make sure the issue is in the plugin with content length calculation or on the provider side

**Comment by oleewere** [comment]
@shibug , for some reason i could not reproduce this for days now. you can try out version 0.2.1 with `@log_level` debug and `enable_retry` true options (retry will only apply against flush for now, also make sense to use retry_max_times option to not block the processing, for configuration see: https://docs.fluentd.org/buffer#configuration-example)

**Comment by shibug** [comment]
I am running 3 instances of fluentd with the same configuration.  Is it possible that this issue is happening when 2 instances of the fluentd is trying to write to the same blob in ADLS? The 3 instances of fluentd are docker containers defined as a service in docker swarm.

I haven't tried the latest version with the retry feature yet and will report back soon

**Comment by oleewere** [comment]
@shibug i think i saw this with one instance as well, (retry should get the blob properties again and count the positions based on that) if multi instance cause any issue like this, then worth to include hostname in the blob output

**Comment by shibug** [comment]
This is the final configuration and it is working great. This issue no longer occurring. Closing this issue.
```
<store>
      @type azurestorage_gen2
      azure_storage_account   adls
      azure_instance_msi      /subscriptions/my-msi                              
      azure_container         test
      skip_container_check    true
      time_slice_format       %Y-%m-%d-%H
      path                    "from-test/${tag[1]}/${tag[2]}/%Y/%m/%d"
      azure_object_key_format "%{path}/${tag[1]}-${tag[2]}-events-%{time_slice}_%{index}-#{Socket.gethostname}.%{file_extension}"
      format                  json
      include_time_key        true
      time_format             %Y-%m-%dT%H:%M:%S.%LZ
      store_as                gzip
      enable_retry            true
      <buffer tag,time>
        @type file
        path /fluentd/buffer
        timekey 5m
        timekey_wait 0s
        timekey_use_utc true
        chunk_limit_size 64m
        overflow_action block
        retry_max_times 10
        disable_chunk_backup true        
      </buffer>
    </store>
```
I have tested this by running 4 instances of fluentd as separate docker containers against millions of messages of various types and length. Each fluentd instance have its own buffer and writing to its own blob. In a 24 hours, I have seen about 20 "failed to flush the buffer" warning due to "Get blob properties" but they succeeded upon next retry. I also counted the consistency of the data as well as the integrity of the compressed file. Everything checks out well. Thanks for all the help @oleewere
