### ISSUE TITLE
Provide support for private endpoint

### ISSUE THREAD

**Issue by shibug** [oleewere/fluent-plugin-azurestorage-gen2#6]
Our ADLS is accessible only over [private endpoint](https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-overview). 
Please enable an option to support providing the full FDQN to ADLS endpoint.

Instead of providing azure_storage_account configuration option, we will provide the full FQDN to the ADLS private endpoint as a new configuration option.

So, the URL will be replaced from https://mystorageaccount.dfs.core.windows.net/ to https://mystorageaccount.custom.domain.com

**Comment by oleewere** [comment]
done in https://github.com/oleewere/fluent-plugin-azurestorage-gen2/commit/cf1f249981b7decd7853982c10d0d05ad806812e

**Comment by shibug** [comment]
This did not work, not sure why.  The debug log doesn't print out the endpoint.  I will find out and report back to you the root cause

**Comment by shibug** [comment]
My understanding of private endpoints was wrong.  The FQDN of ADLS doesn't change.  It will still be: https://mystorageaccount.dfs.core.windows.net/
the underlying DNS change will ensure data is transmitted over the private link established in a private endpoint.

Sorry for the confusion, you may remove the `url_domain_suffix` config parameter.  Not required anymore.

**Comment by shibug** [comment]
For further reading: https://docs.microsoft.com/en-us/azure/storage/common/storage-private-endpoints#dns-changes-for-private-endpoints

**Comment by oleewere** [comment]
@shibug url_domain_suffix can be useful for azure gov, could be it will change something like: `gov_enabled` which can change domain suffixes to dfs.core.windows.net to dfs.core.usgovcloudapi.net
