### ISSUE TITLE
failed to flush the buffer with InternalError error message

### ISSUE THREAD

**Issue by shibug** [oleewere/fluent-plugin-azurestorage-gen2#7]
I am running the latest version (v0.2.4) in an environment where only 1 instance of fluentd is running.  Receiving this error intermittently which makes me think I am definitely losing messages:

> 2020-02-14 18:49:14 +0000 [error]: #0 failed to flush the buffer, and hit limit for retries. dropping all chunks in the buffer queue. retry_times=10 records=1 error_class=Fluent::Plugin::BlobOperationError error="Blob flush request failed - code: 500, body: {\"error\":{\"code\":\"InternalError\",\"message\":\"Server encountered an internal error. Please try again after some time.\\nRequestId:7797b59a-001f-006e-3567-e3442b000000\\nTime:2020-02-14T18:49:14.7306530Z\"}}, headers: {\"Content-Length\"=>\"201\", \"Content-Type\"=>\"application/json;charset=utf-8\", \"Server\"=>\"Windows-Azure-HDFS/1.0 Microsoft-HTTPAPI/2.0\", \"x-ms-error-code\"=>\"InternalError\", \"x-ms-request-id\"=>\"7797b59a-001f-006e-3567-e3442b000000\", \"x-ms-version\"=>\"2018-11-09\", \"Date\"=>\"Fri, 14 Feb 2020 18:49:14 GMT\"}"

My fluentd conf is:

```
<store>
      @type azurestorage_gen2
      @log_level debug
      azure_storage_account   mystorageaccount
      azure_instance_msi      /subscriptions/my-msi                              
      azure_container         mycont
      skip_container_check    true
      time_slice_format       %Y-%m-%d-%H
      path                    "from-test/${tag[1]}/${tag[2]}/%Y/%m/%d"
      azure_object_key_format "%{path}/${tag[1]}-${tag[2]}-events-%{time_slice}_%{index}-#{Socket.gethostname}.%{file_extension}"
      format                  json
      include_time_key        true
      time_format             %Y-%m-%dT%H:%M:%S.%LZ
      store_as                gzip
      enable_retry            true
      <buffer tag,time>
        @type file
        path /fluentd/buffer
        timekey 5m
        timekey_wait 0s
        timekey_use_utc true
        chunk_limit_size 64m
        retry_max_times 10
        flush_thread_count 2
      </buffer>
    </store>
```
Is something wrong with my buffer configuration?  I am not able to determine if I am losing any messages.  The warning message above makes me think I am losing messages

**Comment by shibug** [comment]
I think somewhere the files are getting overwritten.  In an hour I generated 16,066 events.  There were 4 instances of fluentd running writing to their own individual files in ADLS.  I counted the events in all 4 files and it is way less than that number.

1558 + 1596 + 1640 + 1601 = 6395 <-- way less than 16,066 events I was expecting.

**Comment by shibug** [comment]
I am still trying to determine if we are losing any log messages.

**Comment by oleewere** [comment]
@shibug , as the response came from server, the error message does not tell too much about what the problem is (if itás on the request side). not sure is there anything that can show a more detailed error from azure side. based on the message that reached the retry limit (if you are enable debug option you should see more what position params were used for the request)

**Comment by shibug** [comment]
The problem could be on my buffer configuration. I am suspecting `flush_thread_count 2 ` is causing some issues. I am now running with `flush_thread_count 1` to see how it works against millions of logs. Please stand by.

**Comment by oleewere** [comment]
@shibug , possibly, I think that could be solved by calling get_blob_properties call before every operation (so not do any calculation with the positions in iteration) and get_properties+create+append operation should be synchronized in order to not even get any conflict (or without syncronization but on retry call with the get properties operation for sure,..) ... at least adding something like this as an optional parameter, implement this would take some time

**Comment by shibug** [comment]
This is the final configuration and it is working great.  This issue no longer occurring. Closing this issue.

```
<store>
      @type azurestorage_gen2
      azure_storage_account   adls
      azure_instance_msi      /subscriptions/my-msi                              
      azure_container         test
      skip_container_check    true
      time_slice_format       %Y-%m-%d-%H
      path                    "from-test/${tag[1]}/${tag[2]}/%Y/%m/%d"
      azure_object_key_format "%{path}/${tag[1]}-${tag[2]}-events-%{time_slice}_%{index}-#{Socket.gethostname}.%{file_extension}"
      format                  json
      include_time_key        true
      time_format             %Y-%m-%dT%H:%M:%S.%LZ
      store_as                gzip
      enable_retry            true
      <buffer tag,time>
        @type file
        path /fluentd/buffer
        timekey 5m
        timekey_wait 0s
        timekey_use_utc true
        chunk_limit_size 64m
        overflow_action block
        retry_max_times 10
        disable_chunk_backup true        
      </buffer>
    </store>
```
I have tested this by running 4 instances of fluentd as separate docker containers against millions of messages of various types and length.  Each fluentd instance have its own buffer and writing to its own blob.  In a 24 hours, I have seen about 20 "failed to flush the buffer" warning but they succeeded upon next retry.  I also counted the consistency of the data as well as the integrity of the compressed file.  Everything checks out well. Thanks for all the help @oleewere
