### ISSUE TITLE
Chunks from previous day are written to new blobs on current day

### ISSUE THREAD

**Issue by shibug** [oleewere/fluent-plugin-azurestorage-gen2#8]
When the path configuration has date separator, the last hour (2300) chunks are written in two directories.  No duplicates for that hour, it is just splitted into two blobs, one in the previous day path and the other in the current day path.

Example:
from-test/domain/topic/2020/02/16/domain-topic-events-2020-02-16-23_0-a70b606e695c.gz
from-test/domain/topic/2020/02/17/domain-topic-events-2020-02-16-23_0-a70b606e695c.gz

My configuration

```
<store>
      @type azurestorage_gen2
      azure_storage_account   adls
      azure_instance_msi      /subscriptions/my-msi                              
      azure_container         my-cont
      skip_container_check    true
      time_slice_format       %Y-%m-%d-%H
      path                    "from-test/${tag[1]}/${tag[2]}/%Y/%m/%d"
      azure_object_key_format "%{path}/${tag[1]}-${tag[2]}-events-%{time_slice}_%{index}-#{Socket.gethostname}.%{file_extension}"
      format                  json
      include_time_key        true
      time_format             %Y-%m-%dT%H:%M:%S.%LZ
      store_as                gzip
      enable_retry            true
      <buffer tag,time>
        @type file
        path /fluentd/buffer
        timekey 5m
        timekey_wait 0s
        timekey_use_utc true
        chunk_limit_size 64m
        overflow_action block
        retry_max_times 10
        disable_chunk_backup true        
      </buffer>
    </store>
```

**Comment by oleewere** [comment]
@shibug , thanks for testing this out. that can be something to do with the file naming, like in the s3 plugin working like this: if you upload something at 0:20, the filename is based on when it started to gather the logs so the timestamp in the name will be 0-15 not 0-20, here the naming is based on when it was uploaded (0-20 the app started to upload at 0:20) ... that will also need some time, as I got some other work to do as well, but I will look around that code

**Comment by shibug** [comment]
It is happening only on the last hour (23) of the day, which makes me think that when you are about to upload that chunk to ADLS, you are constructing the path (not the file name) based on the current time instead of the chunk time.

Please note the file naming is correct, it is going by the chunk time.So, 23:55 chunk is being written to file: xxx-YYYY-MM-DD-23.gz.  However the path is using the current time.  So, this chunk will be written at 0000 hours the next day.  So, path becomes: /adls/YYYY/MM/DD+1/

So, full FQDN becomes: /adls/YYYY/MM/DD+1/xxx-YYYY-MM-DD-23.gz
instead of: /adls/YYYY/MM/DD/xxx-YYYY-MM-DD-23.gz

**Comment by shibug** [comment]
I believe the change is here: https://github.com/oleewere/fluent-plugin-azurestorage-gen2/blob/85f5b1b8f025a52730eabbeb97fb59e5ccedbaf3/lib/fluent/plugin/out_azurestorage_gen2.rb#L183

Where the path is constructed from current time instead of the time in the metadata.  The file name is constructed correctly

**Comment by oleewere** [comment]
@shibug , yes actually we talked about the same but your explanation is more technical (i wanted to use actual time during the upload), as i did not know about this issue when I did that I could use the same strategy that is used in s3 plugin, the fix is here: https://github.com/oleewere/fluent-plugin-azurestorage-gen2/commit/6aced8a421d2889c4b50c1466ee72c94a33fc3ad
I did not released this yet, will require some testing before i will do that

**Comment by oleewere** [comment]
@shibug , I'm closing this as it's released, feel free to re-open if you see any bugs around the change
