### ISSUE TITLE
Azure Gov: UnrecoverableError error="Get container request failed - code: 0

### ISSUE THREAD

**Issue by rjohnson318** [oleewere/fluent-plugin-azurestorage-gen2#9]
I am working in Azure Government and I want to send the logs to my storage account. But I keep getting the below error. In my experience usually the endpoint points to the public cloud instead of the govt cloud, could that be the issue here?

2020-02-28 15:28:45 +0000 [error]: #0 Get container request failed - code: 0, headers: {} error_class=Fluent::UnrecoverableError error="Get container request failed - code: 0, headers: {}"

**Comment by oleewere** [comment]
@rjohnson318 have you used the `url_domain_suffix` (https://github.com/oleewere/fluent-plugin-azurestorage-gen2#url_domain_suffix) option? 
if that's still an issue after setting the url suffix, this could be because for getting the token this resource is used: `https://storage.azure.com/`, could be different for gov cloud (?) 

you still have an option `azure_oauth_use_azure_cli`(https://github.com/oleewere/fluent-plugin-azurestorage-gen2#azure_oauth_use_azure_cli-preview)  if az cli available on the host.

**Comment by rjohnson318** [comment]
@oleewere thx for the reply I will look at the other options. Also, for gov cloud ik its a different endpoint i just don't know how to find it off the top of my head, I'll have to research it.

**Comment by oleewere** [comment]
@rjohnson318 , sorry it seems az using that storage url as well so i have added an option for it: 
https://github.com/oleewere/fluent-plugin-azurestorage-gen2/commit/7d1ab4efde42871fe3f24d9ef2d3b10779497274
will create a release for that. (if that token thing is an issue, won't hurt if there is an option for that)
my guess the endpoint for gov could look like this: `dfs.core.usgovcloudapi.net`

**Comment by rjohnson318** [comment]
@oleewere found this on the internet for the enpoints

Service type | Azure public | Azure Government
-- | -- | --
Blob storage | *.blob.core.windows.net | *.blob.core.usgovcloudapi.net
Queue storage | *.queue.core.windows.net | *.queue.core.usgovcloudapi.net
Table storage | *.table.core.windows.net | *.table.core.usgovcloudapi.net
File storage | *.file.core.windows.net | *.file.core.usgovcloudapi.net

**Comment by oleewere** [comment]
this tool using the datalake storage api not the blob one, i do not see gen2 storage listed there, so not sure it's supported for gov or not
i have found only one reference on the net, but probably ".dfs.core.usgovcloudapi.net" could work here (at least for the url suffix, not sure about the token)

**Comment by rjohnson318** [comment]
that sounds about right, do you happen to know of another plugin that will copy logs to azure storage account from fluentd?

**Comment by oleewere** [comment]
@rjohnson318 , sure
https://github.com/microsoft/fluent-plugin-azure-storage-append-blob and https://github.com/htgc/fluent-plugin-azurestorage
- it seems second one is not really maintained
- no MSI support for both (you need to use access keys)
- both using blob APIs not dfs
- using the blob api with adls gen2 make sure your hierarchical namespace settings are right
see: https://docs.microsoft.com/bs-cyrl-ba/azure/storage/blobs/data-lake-storage-known-issues#blob-storage-apis (not sure only append has an impact on that or not)

**Comment by rjohnson318** [comment]
@oleewere thanks for the information I am going to try all of the options and see which one works and if I get it to work, Ill let you know what I did and maybe something could be built for us azuregov folks

**Comment by oleewere** [comment]
@rjohnson318 , ok I guess those fluentd plugins won't support this as well, they are using azure sdk, but no option for custom/gov endpoints. I think it worth to check the <storage_acctoun>.dfs.core.usgovcloudapi.net endpoint (i do not have gov account so im not sure that works), maybe it's not documented but works fine (as the datalake gen2 api works well with both WASB and ABFS)

**Comment by oleewere** [comment]
closing it, feel free to reopen it if that will be still required and sure the address with `.dfs.usgovcloudapi.net` won't work
